#!/usr/bin/env python3
"""Generate drug report pages for documentation site.

Creates Markdown pages for each drug with repurposing predictions,
evidence summary, and links to external resources.

Usage:
    uv run python scripts/batch_generate_reports.py [--limit N]

Output:
    docs/_drugs/{drug}.md
"""

import argparse
import json
import re
import sys
from datetime import datetime
from pathlib import Path

import pandas as pd

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))


def slugify(text: str) -> str:
    """Convert text to URL-safe slug."""
    slug = text.lower()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    slug = re.sub(r"-+", "-", slug)
    return slug.strip("-")


def generate_drug_page(
    drug: str,
    drugbank_id: str,
    indications: list[dict],
    evidence: dict | None = None,
) -> str:
    """Generate Markdown content for a drug page.

    Args:
        drug: Drug name
        drugbank_id: DrugBank ID
        indications: List of indication dictionaries
        evidence: Optional evidence bundle

    Returns:
        Markdown content
    """
    slug = slugify(drug)
    now = datetime.now().strftime("%Y-%m-%d")

    # Front matter
    content = f"""---
layout: default
title: {drug}
parent: Drugs
nav_order: 1
last_modified_date: {now}
---

# {drug}

{{: .warning }}
> **Disclaimer**: These predictions are for research purposes only. They do not constitute medical advice and require clinical validation.

## Overview

| Property | Value |
|----------|-------|
| Drug Name | {drug} |
| DrugBank ID | [{drugbank_id}](https://go.drugbank.com/drugs/{drugbank_id}) |
| PNF Status | Listed in Philippine National Formulary |
| Predictions | {len(indications)} potential indications |

## Predicted Indications

The following indications are predicted based on TxGNN knowledge graph analysis:

| Indication | Source | Evidence |
|------------|--------|----------|
"""

    # Add indications
    for ind in indications[:20]:  # Limit to top 20
        disease = ind.get("potential_indication", "")
        source = ind.get("source", "TxGNN")
        evidence_level = "L5"  # Default

        content += f"| {disease} | {source} | {evidence_level} |\n"

    # Evidence section
    content += """
## Evidence Summary

"""

    if evidence:
        trials = evidence.get("sources", {}).get("clinicaltrials", {})
        pubmed = evidence.get("sources", {}).get("pubmed", {})

        content += f"""### Clinical Trials

- **ClinicalTrials.gov**: {trials.get('count', 0)} trials found
- [Search ClinicalTrials.gov](https://clinicaltrials.gov/search?term={drug})

### Literature

- **PubMed**: {pubmed.get('count', 0)} publications found
- [Search PubMed](https://pubmed.ncbi.nlm.nih.gov/?term={drug})

"""
    else:
        content += f"""- [Search ClinicalTrials.gov](https://clinicaltrials.gov/search?term={drug})
- [Search PubMed](https://pubmed.ncbi.nlm.nih.gov/?term={drug})
- [View on DrugBank](https://go.drugbank.com/drugs/{drugbank_id})

"""

    # External links
    content += f"""## External Resources

- [DrugBank: {drug}](https://go.drugbank.com/drugs/{drugbank_id})
- [PubChem](https://pubchem.ncbi.nlm.nih.gov/#query={drug})
- [Wikipedia](https://en.wikipedia.org/wiki/{drug.replace(' ', '_')})

---

*Generated by PhTxGNN on {now}*
"""

    return content


def main():
    parser = argparse.ArgumentParser(
        description="Generate drug report pages"
    )
    parser.add_argument("--limit", type=int, default=100, help="Max drugs to process")
    parser.add_argument("--force", action="store_true", help="Overwrite existing pages")

    args = parser.parse_args()

    print("=" * 60)
    print("Generate Drug Report Pages")
    print("=" * 60)
    print()

    base_dir = Path(__file__).parent.parent
    candidates_path = base_dir / "data" / "processed" / "repurposing_candidates.csv"
    mapping_path = base_dir / "data" / "processed" / "drugbank_mapping.csv"

    if not candidates_path.exists():
        print(f"Error: Candidates file not found: {candidates_path}")
        print("Please run run_kg_prediction.py first.")
        return

    # Load data
    candidates_df = pd.read_csv(candidates_path)
    print(f"Loaded {len(candidates_df)} repurposing candidates")

    mapping_df = pd.read_csv(mapping_path) if mapping_path.exists() else None

    # Group by drug
    drug_groups = candidates_df.groupby("ingredient")

    # Output directory
    drugs_dir = base_dir / "docs" / "_drugs"
    drugs_dir.mkdir(parents=True, exist_ok=True)

    # Create index page
    index_content = """---
layout: default
title: Drugs
nav_order: 2
has_children: true
---

# Drug Reports

Browse drug repurposing predictions for Philippine National Formulary drugs.

| Drug | DrugBank ID | Predictions |
|------|-------------|-------------|
"""

    # Generate pages
    drugs_processed = 0
    drugs_list = list(drug_groups.groups.keys())[:args.limit]

    for drug in drugs_list:
        group = drug_groups.get_group(drug)
        indications = group.to_dict("records")

        # Get DrugBank ID
        drugbank_id = group["drugbank_id"].iloc[0] if "drugbank_id" in group.columns else ""
        if pd.isna(drugbank_id):
            drugbank_id = ""

        # Check for evidence bundle
        evidence = None
        evidence_dir = base_dir / "data" / "evidence" / "bundles"
        if evidence_dir.exists():
            # Try to find matching bundle
            for bundle_file in evidence_dir.glob("*.json"):
                if drug.lower().replace(" ", "-") in bundle_file.stem:
                    with open(bundle_file, "r", encoding="utf-8") as f:
                        evidence = json.load(f)
                    break

        # Generate page
        slug = slugify(drug)
        page_path = drugs_dir / f"{slug}.md"

        if page_path.exists() and not args.force:
            print(f"[SKIP] {drug} (exists)")
            continue

        content = generate_drug_page(drug, drugbank_id, indications, evidence)

        with open(page_path, "w", encoding="utf-8") as f:
            f.write(content)

        drugs_processed += 1
        print(f"[OK] {drug} ({len(indications)} indications)")

        # Add to index
        db_link = f"[{drugbank_id}](https://go.drugbank.com/drugs/{drugbank_id})" if drugbank_id else "N/A"
        index_content += f"| [{drug}](/drugs/{slug}/) | {db_link} | {len(indications)} |\n"

    # Save index
    index_path = drugs_dir.parent / "drugs.md"
    with open(index_path, "w", encoding="utf-8") as f:
        f.write(index_content)

    print()
    print(f"Generated {drugs_processed} drug pages")
    print(f"Pages saved to: {drugs_dir}")
    print(f"Index saved to: {index_path}")


if __name__ == "__main__":
    main()
