#!/usr/bin/env python3
"""Build documentation site.

Generates all necessary files for the Jekyll documentation site,
including drug pages, indices, and static assets.

Usage:
    uv run python scripts/build_docs.py [--serve]

Output:
    docs/ (Jekyll site ready for deployment)
"""

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

import pandas as pd


def generate_statistics_page(base_dir: Path) -> str:
    """Generate statistics page content.

    Args:
        base_dir: Project base directory

    Returns:
        Markdown content
    """
    candidates_path = base_dir / "data" / "processed" / "repurposing_candidates.csv.gz"
    mapping_path = base_dir / "data" / "processed" / "drugbank_mapping.csv"

    stats = {
        "total_drugs": 0,
        "mapped_drugs": 0,
        "total_predictions": 0,
        "unique_diseases": 0,
    }

    if candidates_path.exists():
        df = pd.read_csv(candidates_path)
        stats["total_predictions"] = len(df)
        stats["total_drugs"] = df["ingredient"].nunique()
        stats["unique_diseases"] = df["potential_indication"].nunique()

    if mapping_path.exists():
        mapping_df = pd.read_csv(mapping_path)
        stats["mapped_drugs"] = mapping_df["mapped"].sum() if "mapped" in mapping_df.columns else 0

    now = datetime.now().strftime("%Y-%m-%d")

    content = f"""---
layout: default
title: Statistics
nav_order: 3
---

# Statistics

Last updated: {now}

## Overview

| Metric | Value |
|--------|-------|
| Total PNF Drugs | {stats['total_drugs']} |
| DrugBank Mapped | {stats['mapped_drugs']} |
| Mapping Rate | {stats['mapped_drugs']/stats['total_drugs']*100:.1f}% |
| Total Predictions | {stats['total_predictions']:,} |
| Unique Diseases | {stats['unique_diseases']} |

## Data Sources

- **Philippine National Formulary (PNF)**: Essential Medicines List, 8th Edition (2022)
- **TxGNN Knowledge Graph**: Drug-disease relationship predictions
- **DrugBank**: Drug identifier standardization

## Methodology

1. **Drug Extraction**: Extract drug names from PNF-EML 2022
2. **DrugBank Mapping**: Map drug names to standard DrugBank identifiers
3. **TxGNN Prediction**: Use knowledge graph to identify potential indications
4. **Evidence Collection**: Gather supporting evidence from ClinicalTrials.gov and PubMed

## Evidence Levels

| Level | Description |
|-------|-------------|
| L1 | Systematic review / Meta-analysis |
| L2 | Randomized controlled trial (Phase 3/4) |
| L3 | Early phase clinical trial (Phase 1/2) |
| L4 | Case series / Case reports |
| L5 | Expert opinion / Knowledge graph prediction |

---

*Generated by PhTxGNN*
"""

    return content


def generate_about_page() -> str:
    """Generate about page content.

    Returns:
        Markdown content
    """
    return """---
layout: default
title: About
nav_order: 4
---

# About PhTxGNN

PhTxGNN is a drug repurposing prediction system for the Philippines,
built using the TxGNN knowledge graph framework.

## What is Drug Repurposing?

Drug repurposing (also known as drug repositioning) is the process of
finding new therapeutic uses for existing drugs. This approach can
significantly reduce drug development time and costs since the safety
profiles of existing drugs are already well established.

## How It Works

PhTxGNN uses the TxGNN knowledge graph to predict potential new indications
for drugs listed in the Philippine National Formulary (PNF). The system:

1. Maps PNF drugs to standardized DrugBank identifiers
2. Queries the TxGNN knowledge graph for drug-disease relationships
3. Generates FHIR-compatible resources for interoperability
4. Collects supporting evidence from clinical trials and literature

## Disclaimer

{: .warning }
> These predictions are for **research purposes only**. They do not constitute
> medical advice and should not be used for clinical decision-making without
> proper validation by qualified healthcare professionals.

## Technical Details

- **Knowledge Graph**: TxGNN (Harvard Dataverse)
- **Drug Standard**: DrugBank identifiers
- **Interoperability**: FHIR R4 resources
- **Data Source**: Philippine National Formulary 8th Edition (2022)

## Links

- [FHIR API](/fhir/metadata)
- [SMART App](/smart/launch.html)
- [GitHub Repository](https://github.com/phtxgnn/phtxgnn)

## Contact

For questions or feedback, please open an issue on GitHub.

---

*PhTxGNN - Philippine Drug Repurposing using TxGNN*
"""


def build_docs(base_dir: Path, serve: bool = False):
    """Build the documentation site.

    Args:
        base_dir: Project base directory
        serve: Whether to start local server
    """
    docs_dir = base_dir / "docs"

    print("=" * 60)
    print("Build Documentation Site")
    print("=" * 60)
    print()

    # Generate statistics page
    print("Generating statistics page...")
    stats_content = generate_statistics_page(base_dir)
    with open(docs_dir / "statistics.md", "w", encoding="utf-8") as f:
        f.write(stats_content)

    # Generate about page
    print("Generating about page...")
    about_content = generate_about_page()
    with open(docs_dir / "about.md", "w", encoding="utf-8") as f:
        f.write(about_content)

    # Generate drug reports
    print("\nGenerating drug reports...")
    subprocess.run(
        [sys.executable, str(base_dir / "scripts" / "batch_generate_reports.py")],
        cwd=base_dir,
    )

    # Check for Jekyll
    print("\nChecking Jekyll installation...")
    gemfile = docs_dir / "Gemfile"
    if not gemfile.exists():
        print("Warning: Gemfile not found. Run 'bundle install' in docs/ directory.")
        return

    # Build or serve
    if serve:
        print("\nStarting local Jekyll server...")
        print("Visit http://localhost:4000 to view the site")
        print("Press Ctrl+C to stop")
        print()

        try:
            subprocess.run(
                ["bundle", "exec", "jekyll", "serve"],
                cwd=docs_dir,
            )
        except KeyboardInterrupt:
            print("\nServer stopped.")
    else:
        print("\nBuilding site...")
        result = subprocess.run(
            ["bundle", "exec", "jekyll", "build"],
            cwd=docs_dir,
            capture_output=True,
            text=True,
        )

        if result.returncode == 0:
            print("Site built successfully!")
            print(f"Output: {docs_dir / '_site'}")
        else:
            print("Build failed:")
            print(result.stderr)


def main():
    parser = argparse.ArgumentParser(
        description="Build documentation site"
    )
    parser.add_argument("--serve", action="store_true",
                       help="Start local development server")

    args = parser.parse_args()

    base_dir = Path(__file__).parent.parent
    build_docs(base_dir, args.serve)


if __name__ == "__main__":
    main()
