#!/usr/bin/env python3
"""Process Philippine National Formulary (PNF) Essential Medicines List data.

Extracts drug names from PNF-EML 2022 (8th Edition) and converts to standard JSON format.

Usage:
    uv run python scripts/process_fda_data.py

Output:
    data/raw/ph_fda_drugs.json
"""

import json
from pathlib import Path
from typing import List, Dict


# Drug names extracted from PNF-EML 2022 (8th Edition)
# Source: Department of Health Philippines, Pharmaceutical Division
# https://pharmadiv.doh.gov.ph
PNF_DRUGS = [
    # A
    "Abacavir",
    "Acetazolamide",
    "Acetylcysteine",
    "Aciclovir",
    "Activated Charcoal",
    "Adenosine",
    "Albendazole",
    "Albumin, Human",
    "Alendronate",
    "Alfuzosin",
    "Allopurinol",
    "Alprazolam",
    "Aluminum Hydroxide",
    "Amikacin",
    "Aminophylline",
    "Amiodarone",
    "Amlodipine",
    "Amoxicillin",
    "Amphotericin B",
    "Ampicillin",
    "Anastrazole",
    "Anti-D Immunoglobulin",
    "Antilymphocyte Immunoglobulin",
    "Antithymocyte Immunoglobulin",
    "Aripiprazole",
    "Artemether",
    "Artesunate",
    "Ascorbic Acid",
    "Asparaginase",
    "Aspirin",
    "Atenolol",
    "Atorvastatin",
    "Atracurium",
    "Atropine",
    "Azathioprine",
    "Azithromycin",
    "Aztreonam",

    # B
    "Bacitracin",
    "Baclofen",
    "Barium Sulfate",
    "Basiliximab",
    "BCG Vaccine",
    "Bedaquiline",
    "Benzoyl Peroxide",
    "Benzyl Benzoate",
    "Beractant",
    "Betahistine",
    "Betamethasone",
    "Betaxolol",
    "Bicalutamide",
    "Biperiden",
    "Bisacodyl",
    "Bisoprolol",
    "Bleomycin",
    "Brimonidine",
    "Brinzolamide",
    "Bromazepam",
    "Bromocriptine",
    "Budesonide",
    "Bumetanide",
    "Bupivacaine",
    "Butamirate",
    "Butorphanol",

    # C
    "Calamine",
    "Calcipotriol",
    "Calcitriol",
    "Calcium Carbonate",
    "Calcium Folinate",
    "Calcium Gluconate",
    "Calcium Sennosides",
    "Capecitabine",
    "Capreomycin",
    "Captopril",
    "Carbachol",
    "Carbamazepine",
    "Carbetocin",
    "Carboplatin",
    "Carboprost",
    "Carboxymethylcellulose",
    "Carvedilol",
    "Castor Oil",
    "Cefalexin",
    "Cefazolin",
    "Cefepime",
    "Cefixime",
    "Cefotaxime",
    "Cefoxitin",
    "Ceftazidime",
    "Ceftriaxone",
    "Cefuroxime",
    "Celecoxib",
    "Cetirizine",
    "Chlorambucil",
    "Chloramphenicol",
    "Chlorhexidine",
    "Chloroquine",
    "Chlorphenamine",
    "Chlorpromazine",
    "Ciclosporin",
    "Cilostazol",
    "Cinnarizine",
    "Ciprofloxacin",
    "Cisplatin",
    "Clarithromycin",
    "Clindamycin",
    "Clobetasol",
    "Clofazimine",
    "Clomifene",
    "Clonazepam",
    "Clonidine",
    "Clopidogrel",
    "Clotrimazole",
    "Cloxacillin",
    "Clozapine",
    "Codeine",
    "Colchicine",
    "Colistin",
    "Conjugated Estrogen",
    "Cotrimoxazole",
    "Crotamiton",
    "Cyclophosphamide",
    "Cycloserine",
    "Cyproterone",
    "Cytarabine",

    # D
    "Dacarbazine",
    "Daclatasvir",
    "Dactinomycin",
    "Danazol",
    "Dantrolene",
    "Dapsone",
    "Deferiprone",
    "Deferasirox",
    "Deferoxamine",
    "Delamanid",
    "Desflurane",
    "Desmopressin",
    "Dexamethasone",
    "Dextran",
    "Dextromethorphan",
    "Diazepam",
    "Diclofenac",
    "Dicycloverine",
    "Diethylcarbamazine",
    "Digoxin",
    "Diloxanide",
    "Diltiazem",
    "Dimercaprol",
    "Diphenhydramine",
    "Diphtheria Antitoxin",
    "Dipyridamole",
    "Divalproex Sodium",
    "Dobutamine",
    "Docetaxel",
    "Dolutegravir",
    "Domperidone",
    "Donepezil",
    "Dopamine",
    "Dorzolamide",
    "Doxorubicin",
    "Doxycycline",
    "Dydrogesterone",

    # E
    "Efavirenz",
    "Emtricitabine",
    "Enalapril",
    "Enoxaparin",
    "Entecavir",
    "Ephedrine",
    "Eperisone",
    "Epinephrine",
    "Epirubicin",
    "Epoetin Alfa",
    "Epoetin Beta",
    "Ergotamine",
    "Ertapenem",
    "Erythromycin",
    "Escitalopram",
    "Esmolol",
    "Ethambutol",
    "Ethinylestradiol",
    "Etonogestrel",
    "Etoposide",
    "Everolimus",

    # F
    "Factor VIII",
    "Factor IX",
    "Famotidine",
    "Felodipine",
    "Fenofibrate",
    "Fentanyl",
    "Ferrous Sulfate",
    "Filgrastim",
    "Finasteride",
    "Fluconazole",
    "Flucytosine",
    "Flumazenil",
    "Flunarizine",
    "Fluocinonide",
    "Fluorescein",
    "Fluorouracil",
    "Fluoxetine",
    "Flupentixol",
    "Fluphenazine",
    "Flutamide",
    "Fluticasone",
    "Folic Acid",
    "Fomepizole",
    "Fondaparinux",
    "Formoterol",
    "Fosfomycin",
    "Furosemide",
    "Fusidic Acid",

    # G
    "Gabapentin",
    "Gadobutrol",
    "Gadoteric acid",
    "Ganciclovir",
    "Gemcitabine",
    "Gentamicin",
    "Gliclazide",
    "Glucagon",
    "Glucose",
    "Glycerol",
    "Glyceryl trinitrate",
    "Goserelin",

    # H
    "Haloperidol",
    "Halothane",
    "Heparin",
    "Hepatitis A Vaccine",
    "Hepatitis B Immunoglobulin",
    "Hepatitis B Vaccine",
    "Human Papillomavirus Vaccine",
    "Hydralazine",
    "Hydrochlorothiazide",
    "Hydrocortisone",
    "Hydrogen Peroxide",
    "Hydroxychloroquine",
    "Hydroxyethyl Starch",
    "Hydroxyurea",
    "Hydroxyzine",
    "Hyoscine",
    "Hypromellose",

    # I
    "Ibuprofen",
    "Idarubicin",
    "Ifosfamide",
    "Imatinib",
    "Imiglucerase",
    "Imiquimod",
    "Immunoglobulin",
    "Indacaterol",
    "Indapamide",
    "Influenza Vaccine",
    "Insulin Glargine",
    "Interferon Alfa",
    "Iodine",
    "Iodixanol",
    "Iohexol",
    "Iopamidol",
    "Iopromide",
    "Iothalamate",
    "Ioversol",
    "Ipratropium",
    "Irbesartan",
    "Irinotecan",
    "Iron sucrose",
    "Isoflurane",
    "Isoniazid",
    "Isosorbide Dinitrate",
    "Isosorbide Mononitrate",
    "Isoxsuprine",
    "Itraconazole",
    "Ivermectin",

    # K
    "Kanamycin",
    "Ketamine",
    "Ketoconazole",
    "Ketoprofen",
    "Ketorolac",

    # L
    "Lactulose",
    "Lagundi",
    "Lamivudine",
    "Lamotrigine",
    "Lansoprazole",
    "Latanoprost",
    "Letrozole",
    "Leucovorin",
    "Leuproreline",
    "Levetiracetam",
    "Levobupivacaine",
    "Levodopa",
    "Levofloxacin",
    "Levonorgestrel",
    "Levothyroxine",
    "Lidocaine",
    "Linezolid",
    "Lithium Carbonate",
    "Loperamide",
    "Lopinavir",
    "Loratadine",
    "Losartan",
    "Lynestrenol",

    # M
    "Magnesium Sulfate",
    "Mannitol",
    "Mebendazole",
    "Mebeverine",
    "Mecobalamin",
    "Medroxyprogesterone",
    "Mefenamic Acid",
    "Mefloquine",
    "Megestrol",
    "Melphalan",
    "Memantine",
    "Meningococcal Vaccine",
    "Mercaptopurine",
    "Meropenem",
    "Mesalazine",
    "Mesna",
    "Metformin",
    "Methimazole",
    "Methotrexate",
    "Methyldopa",
    "Methylene Blue",
    "Methylergometrine",
    "Methylphenidate",
    "Methylprednisolone",
    "Metoclopramide",
    "Metoprolol",
    "Metronidazole",
    "Micafungin",
    "Miconazole",
    "Midazolam",
    "Mitoxantrone",
    "Mometasone",
    "Montelukast",
    "Morphine",
    "Moxifloxacin",
    "Mupirocin",
    "Mycophenolate Mofetil",
    "Mycophenolic Acid",

    # N
    "N-acetyl Penicillamine",
    "Nalbuphine",
    "Nalidixic Acid",
    "Naloxone",
    "Naltrexone",
    "Naproxen",
    "Neomycin",
    "Neostigmine",
    "Nepafenac",
    "Nevirapine",
    "Nicardipine",
    "Nicotine",
    "Nifedipine",
    "Nimodipine",
    "Nitrofurantoin",
    "Nitroglycerin",
    "Nitrous Oxide",
    "Norepinephrine",
    "Norethisterone",
    "Nystatin",

    # O
    "Octreotide",
    "Ofloxacin",
    "Olanzapine",
    "Olodaterol",
    "Omeprazole",
    "Ondansetron",
    "Oseltamivir",
    "Oxacillin",
    "Oxaliplatin",
    "Oxcarbazepine",
    "Oxycodone",
    "Oxygen",
    "Oxymetazoline",
    "Oxytocin",

    # P
    "Paclitaxel",
    "Paliperidone",
    "Pancuronium",
    "Pantoprazole",
    "Para-amino salicylic acid",
    "Paracetamol",
    "Peginterferon Alfa",
    "Penicillin G Benzathine",
    "Penicillin G Crystalline",
    "Permethrin",
    "Pethidine",
    "Phenobarbital",
    "Phenoxymethyl Penicillin",
    "Phenylephrine",
    "Phenytoin",
    "Physostigmine",
    "Phytomenadione",
    "Pilocarpine",
    "Piperacillin",
    "Pneumococcal Vaccine",
    "Polymyxin B",
    "Poractant alfa",
    "Potassium Chloride",
    "Potassium Citrate",
    "Potassium Phosphate",
    "Povidone Iodine",
    "Pralidoxime",
    "Praziquantel",
    "Prednisolone",
    "Prednisone",
    "Primaquine",
    "Propofol",
    "Propranolol",
    "Propylthiouracil",
    "Protamine Sulfate",
    "Prothionamide",
    "Proxymetacaine",
    "Pyrazinamide",
    "Pyridostigmine",
    "Pyridoxine",
    "Pyrimethamine",

    # Q
    "Quetiapine",
    "Quinine",

    # R
    "Rabeprazole",
    "Rabies Immunoglobulin",
    "Rabies Vaccine",
    "Ranitidine",
    "Remifentanil",
    "Retinol",
    "Ribavirin",
    "Rifabutin",
    "Rifampicin",
    "Rifapentine",
    "Rifaximin",
    "Rilpivirine",
    "Risperidone",
    "Rituximab",
    "Rivastigmine",
    "Ritonavir",
    "Rocuronium",
    "Ropivacaine",
    "Rosuvastatin",

    # S
    "Sacubitril",
    "Salbutamol",
    "Salicylic Acid",
    "Sambong",
    "Salmeterol",
    "Selegiline",
    "Selenium Sulfide",
    "Sertraline",
    "Sevelamer",
    "Sevoflurane",
    "Silver Sulfadiazine",
    "Simvastatin",
    "Sirolimus",
    "Sodium Bicarbonate",
    "Sodium Calcium Edetate",
    "Sodium Chloride",
    "Sodium Hyaluronate",
    "Sodium Hypochlorite",
    "Sodium Iodide",
    "Sodium Nitrite",
    "Sodium Nitroprusside",
    "Sodium Thiosulfate",
    "Sodium Valproate",
    "Sofosbuvir",
    "Somatostatin",
    "Spectinomycin",
    "Spironolactone",
    "Streptokinase",
    "Streptomycin",
    "Succimer",
    "Sucralfate",
    "Sugammadex",
    "Sulfacetamide",
    "Sulfur",
    "Sumatriptan",
    "Suxamethonium",

    # T
    "Tacrolimus",
    "Tafluprost",
    "Tamoxifen",
    "Tamsulosin",
    "Tazobactam",
    "Tegafur",
    "Telmisartan",
    "Tenofovir",
    "Terazosin",
    "Terbinafine",
    "Terbutaline",
    "Testosterone",
    "Tetanus Immunoglobulin",
    "Tetanus Toxoid",
    "Tetracaine",
    "Tetracycline",
    "Theophylline",
    "Thiamine",
    "Thiopental",
    "Timolol",
    "Tinzaparin",
    "Tiotropium",
    "Tobramycin",
    "Tocilizumab",
    "Tolvaptan",
    "Topiramate",
    "Tramadol",
    "Tranexamic Acid",
    "Trastuzumab",
    "Travoprost",
    "Triclabendazole",
    "Trimetazidine",
    "Trimethoprim",
    "Tropicamide",
    "Tsaang Gubat",

    # U
    "Ursodeoxycholic Acid",

    # V
    "Valaciclovir",
    "Valganciclovir",
    "Valproic Acid",
    "Valsartan",
    "Vancomycin",
    "Varenicline",
    "Varicella Zoster Immunoglobulin",
    "Vasopressin",
    "Vecuronium",
    "Verapamil",
    "Vinblastine",
    "Vincristine",
    "Vitamin A",
    "Vitamin B1",
    "Vitamin B6",
    "Vitamin B12",
    "Vitamin C",
    "Vitamin K1",
    "Voriconazole",

    # W
    "Warfarin",

    # Y
    "Yellow Fever Vaccine",

    # Z
    "Zidovudine",
    "Zinc",
    "Zoledronic Acid",
    "Zolmitriptan",
    "Zolpidem",
]


def normalize_drug_name(name: str) -> str:
    """Normalize drug name for matching."""
    # Remove common suffixes and standardize
    normalized = name.upper().strip()

    # Remove salt forms
    for suffix in [
        " SULFATE", " SULPHATE", " HYDROCHLORIDE", " HCL",
        " MALEATE", " CITRATE", " SODIUM", " POTASSIUM",
        " ACETATE", " TARTRATE", " PHOSPHATE", " FUMARATE",
        " BROMIDE", " CHLORIDE", " LACTATE", " SUCCINATE",
        " MESYLATE", " MESILATE", " BESYLATE", " BESILATE",
    ]:
        if normalized.endswith(suffix):
            normalized = normalized[:-len(suffix)]

    return normalized.strip()


def create_drug_records() -> List[Dict]:
    """Create standardized drug records from PNF list."""
    records = []

    for i, drug_name in enumerate(PNF_DRUGS):
        record = {
            "license_id": f"PNF-{i+1:04d}",
            "brand_name": drug_name,
            "ingredient": normalize_drug_name(drug_name),
            "raw_ingredient": drug_name,
            "source": "PNF-EML 8th Edition (2022)",
            "status": "active",
        }
        records.append(record)

    return records


def main():
    print("=" * 60)
    print("Processing Philippine National Formulary (PNF) Drug Data")
    print("=" * 60)
    print()

    base_dir = Path(__file__).parent.parent
    raw_dir = base_dir / "data" / "raw"
    output_path = raw_dir / "ph_fda_drugs.json"

    # Ensure raw directory exists
    raw_dir.mkdir(parents=True, exist_ok=True)

    # Create drug records
    print(f"Processing {len(PNF_DRUGS)} drugs from PNF-EML 2022...")
    records = create_drug_records()

    # Save to JSON
    print(f"Saving to: {output_path}")
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(records, f, ensure_ascii=False, indent=2)

    print(f"Completed! {len(records)} drug records saved.")
    print()
    print("Next step: Run the DrugBank mapping")
    print("  uv run python scripts/run_kg_prediction.py")


if __name__ == "__main__":
    main()
